import Head from "next/head";
import React from "react";
import LandingpageHero from "../components/landingPageHero";
import LandingPageNextMainSection from "../components/landingPageMainSections";

export default function Home() {
  const [mainSectionVisible, setMainSectionVisible] = React.useState(false);

  const onMouseWheelHandler = (e) => {
    const sign = Math.sign(e.deltaY);
    if (sign == "1") {
      setMainSectionVisible(true);
    } else {
      return;
    }
  };
  // React.useEffect(() => {
  //   window.addEventListener("mousewheel", onMouseWheelHandler);
  //   return () => window.removeEventListener("mousewheel", onMouseWheelHandler);
  // }, []);
  return (
    <>
      <Head>
        <title>Insightful Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="hideScrollBar">
        <div
          onWheel={(e) => onMouseWheelHandler(e)}
          className={mainSectionVisible ? "displayNone" : "displayInitial"}
        >
          <LandingpageHero />
        </div>
        <div className={mainSectionVisible ? "displayInitial" : "displayNone"}>
          <LandingPageNextMainSection />
        </div>
      </main>
    </>
  );
}
